### DISCUSSION TITLE
Working like a charm - any UI ideas to share

### DISCUSSION THREAD

**Discussion by albertusQuelle** [ylabonte/proconip-hass#68] [General]
Thanks, that works like a charm on my HA instance. Have a procon running for my pool from lembi. 

Any nice UI graphics one wants to share? Like graphs or cards etc.?

Cheers

**Comment by ylabonte** [comment]
Hey, cool to hear it’s working well for your pool! 🚀

I'm not the UI guy and don’t have anything super fancy myself, but I did put together a small custom UI element that I find quite handy. Maybe it can serve as a starting point or inspiration for others — and I’d love to see how others are visualizing their procon data! 🙌

Here’s a screenshot of my electrode visualization:
<img width="512" alt="image" src="https://github.com/user-attachments/assets/003eb047-390d-4a09-8191-fe5610f21f66" />

And this is the corresponding YAML for the card:
```yaml
title: Wasserqualität
square: false
type: grid
columns: 1
cards:
  - square: false
    type: grid
    cards:
      - type: gauge
        entity: sensor.redox_sensor
        name: Redox
        unit: mV
        max: 900
        min: 550
        needle: true
        segments:
          - color: "#f7e9f4"
            from: 0
          - color: "#f5daef"
            from: 650
          - color: "#f4cbeb"
            from: 700
          - color: "#f2bce7"
            from: 725
          - color: "#f1ade3"
            from: 750
          - color: "#f09fdf"
            from: 800
      - type: gauge
        entity: sensor.ph_sensor
        name: pH Wert
        needle: true
        min: 6
        max: 8
        segments:
          - color: "#da3d75"
            from: 0
          - color: "#db5580"
            from: 6.2
          - color: "#e0658a"
            from: 6.3
          - color: "#e2749a"
            from: 6.4
          - color: "#e587a7"
            from: 6.5
          - color: "#e799b5"
            from: 6.6
          - color: "#e7abc1"
            from: 6.7
          - color: "#23ab7e"
            from: 6.85
          - color: "#8dc4df"
            from: 7.15
          - color: "#75bada"
            from: 7.3
          - color: "#5fadd2"
            from: 7.4
          - color: "#469fcb"
            from: 7.5
          - color: "#3293c3"
            from: 7.6
          - color: rgb(54, 134, 185)
            from: 7.7
          - color: rgb(53, 122, 175)
            from: 7.8
    columns: 2
  - square: false
    type: grid
    cards:
      - graph: line
        type: sensor
        entity: sensor.redox_sensor
        detail: 2
        name: Redox
      - graph: line
        type: sensor
        entity: sensor.ph_sensor
        detail: 2
        name: pH
    columns: 2
```

Feel free to adjust colors and values and re-post an optimized version... 😁

Cheers!
