### ISSUE TITLE
Redox Wert, gerundeter Wert fehlerhaft?!

### ISSUE THREAD

**Issue by gisbertg** [ylabonte/proconip-hass#15]
<img width="396" alt="Bildschirmfoto 2023-06-06 um 18 12 40" src="https://github.com/ylabonte/proconip-hass/assets/33952887/ce46f107-49fe-418c-b927-5e4d5c6f4daf">
<img width="393" alt="Bildschirmfoto 2023-06-06 um 18 11 51" src="https://github.com/ylabonte/proconip-hass/assets/33952887/de90e96f-0fb3-4d59-9ff6-e66a6cc5bb9e">

Der Wert springt hin und her, nach dem Komma.Das soll nicht so sein, oder?  Geht es mit dem Projekt weiter? Sieht ansonsten ja schon ganz gut aus.

**Comment by ylabonte** [comment]
Sorry, die Integration ist noch in einem allerersten Test-Stadium... und als ich sie selber testen wollte, hat mein altes Notebook den Dienst verweigert. Damit bist du mir quasi sogar schon einen Schritt voraus. 😅 
Dachte nicht, dass schon wer die Integration wahrnimmt und installiert. Werde das Projekt aber in den nächsten Wochen fortsetzen.

Ich lasse das Issue mal offen, bis ich ein erstes Release fertig habe, um dich auf diesem Kanal auf dem Laufenden zu halten bzw. dir hier mitzuteilen, wenn sich eine Aktualisierung bzw. ein erneuter Test/Einsatz der Integration lohnt.

**Comment by gisbertg** [comment]
Danke!
https://www.poolsteuerung.de/viewtopic.php?f=29&start=20&t=1678&sid=dda7376f328568a5bd5ba0649e39f581
Vielleicht hilft dir der Link weiter?!

**Comment by eseppy** [comment]
Hi, 
ich habe mir die Integration auch installiert und bin an weiteren Relais interessiert ;-) Helfe gerne beim testen!

**Comment by ylabonte** [comment]
Die Integration ist jetzt grob überarbeitet und sollte so nun auch einigermaßen funktionieren (Redox + pH Sensoren, mehrere Binary Sensoren und vor allem Switches für alle Relays). Vorher solltet ihr aber die bereits angelegten Konfigurationen (unter Einstellungen -> Integrationen -> _auf das kleine Zahnrad der Integration_ -> _da dann im Kontextmenü den Eintrag löschen_) sowie die zuvor installierte Integration löschen (_wirklich das Verzeichnis `/config/custom_components/proconip` löschen_). Ich musste die Integration umbenennen, weshalb sie jetzt unter `custom_components/proconip_pool_controller` abgelegt wird/werden muss.

**Comment by gisbertg** [comment]
Sieht schon "sehr gut" aus!!!

**Comment by ylabonte** [comment]
Ich hab gerade schon mal die Temperatur-Sensoren ergänzt...

**Comment by gisbertg** [comment]
funktioniert!

**Comment by ylabonte** [comment]
Jetzt gibt es auch
* Analog Kanäle,
* Digitale Inputs,
* Sensoren welche den Status der Relays als Text ausgeben,
* Select-Controls zur alternativen Steuerung von relays (Dropdowns mit _auto_, _on_ und _off_) und
* ich habe mal was ausprobiert, das neu angelegte Sensoren/Controls nur noch dann automatisch in der Übersicht auftauchen sollten, wenn sie nicht mit "n.a." benannt sind. 
Letzteres gilt aber wirklich nur für Sensoren, die mit dem Update neu hinzugefügt werden (oder bspw. bei einer frischen Einrichtung der Integration). Ist aber auch nur ein Versuch, nachdem ich da was in der Doku gesehen habe, das so klang, als ob es deinem Wunsch entspricht (https://developers.home-assistant.io/docs/core/entity; siehe `entity_registry_visible_default`).

**Comment by gisbertg** [comment]
Und die Restinhalte funktionieren auch schon. 👍

**Comment by gisbertg** [comment]
https://community.home-assistant.io/t/how-to-show-3-states-on-a-button/525204
Hier vielleicht eine Idee für einen 3 Wege Button? On/Auto/Off

**Comment by ylabonte** [comment]
Das ist eine Konfiguration/Hilfestellung für die Verwendung von Conditional Cards, also eine Lösung, die man als Anwender nutzen kann. Oder mit anderen Worten, etwas das du selber machen kannst, aber nichts, was ich im Rahmen der Integration einbauen oder out-of-the-box bereitstellen könnte.
Ich glaube aber, die Lösung bringt auch nur einen Button, der mehrere States anzeigen kann. Wünschenswert wäre ja aber ein Button bzw. eine Card, die auch alle drei Schaltflächen bietet. Hierzu müsste man eine Custom Card implementieren (https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/). Will nicht ausschließen, dass ich das noch tue, aber das wird dann ein separates kleines Projekt. 

Komme aber auch erst nächste Woche wieder dazu, mich weiter mit dem Thema auseinanderzusetzen.

**Comment by gisbertg** [comment]
Genau, den Tri-State Button gibt es ja leider nicht. Da muß man tricksen. Hab keine Eile, super Arbeit!

**Comment by ylabonte** [comment]
Ich will nicht ausschließen, dass ich noch etwas eigenes mache. Aber vorerst würde ich Vorschlagen, die `custom:button-card` (gibt's auch über [HACS](https://hacs.xyz/) oder direkt [hier](https://github.com/custom-cards/button-card)) zu nutzen, um Status und alle nötigen Buttons halbwegs schlank abzubilden. Das kann im einfachsten Fall dann etwa so aussehen: 
<img width="490" alt="image" src="https://github.com/ylabonte/proconip-hass/assets/638981/f659ce6c-6e39-425b-91e8-201065ac331b">

Das ist dann zwar kein einzelner Button, der 3 States abbildet, aber zwei Buttons, über die man den aktuellen Status in Form von Auto/Manuell und An/Aus ablesen und umschalten kann.

```yaml
square: false
type: grid
columns: 1
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        color_type: label-card
        name: Filterpumpe
        color: transparent
      - type: custom:button-card
        entity: switch.relay_no_8_poolpumpe_auto_mode
        show_icon: false
        show_name: false
        show_state: true
        state:
          - value: 'on'
            state_display: Auto
          - value: 'off'
            state_display: Manuell
      - type: custom:button-card
        entity: switch.relay_no_8_poolpumpe
        show_icon: false
        show_name: false
        show_state: true
        state:
          - value: 'on'
            state_display: An
          - value: 'off'
            state_display: Aus
```
Die `grid`-Card hier auf oberster Ebene mit `columns: 1` ist lediglich ein Wrapper, um mehrere `custom:button-card`s zu bündeln. Alles ab Zeile 5 kann dann beliebig oft bzw. je Relais kopiert werden. Die `name` und `entity` Attribute müssen natürlich dann jeweils entsprechend angepasst werden.

Das ist aber auch wirklich nur das einfachste Beispiel. Im Idealfall sollte man das wohl über die Konfigurations-Template-Funktion der `custom:button-card` lösen, um nicht immer die gesamte Konfiguration zu kopieren. Außerdem bietet die `custom:button-card` unzählige Möglichkeiten Icons und Farben zu nutzen, um Dinge aufzuhübschen... 

Das Issue hier würde ich ansonsten aber mal ganz gerne schließen. Das ursprüngliche hiermit gemeldet Problem hat sich ja längst geklärt und funktional sollte momentan eigentlich alles im grünen Bereich sein. Sollte dir etwas auffallen, das nicht funktioniert oder wenn du noch einen Verbesserungsvorschlag einreichen möchtest, kannst du dafür gerne jederzeit ein neues Issue eröffnen.
